### Obter todas os sensores
GET http://localhost:8080/sensor

### Obter todas os sensores em controle
GET http://localhost:8080/sensor/controle/30313775-854a-4c45-94c8-634f933eb2a3?pagina=0

### Obter sensor por ID
GET http://localhost:8080/sensor/6b049965-a78e-44dd-84fe-c7faeb7936fe

### Criar sensor
POST http://localhost:8080/sensor/controle/30313775-854a-4c45-94c8-634f933eb2a3
Content-Type: application/json

{
  "tipo": "tipado"
}

### Atualizar sensor
PUT http://localhost:8080/sensor/6b049965-a78e-44dd-84fe-c7faeb7936fe
Content-Type: application/json

{
  "tipo": "Sensor NOVO 2"
}

### Deletar sensor
DELETE http://localhost:8080/sensor/6b049965-a78e-44dd-84fe-c7faeb7936fe